[package]
name = "concurrent-map-bench"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
evmap = { path = "../" }
chashmap = "0.1.2"
clap = "2.20.3"
zipf = "0.2.0"
rand = "0.3"

[profile.release]
debug = true
