[package]
name = "evmap"
version = "6.0.1"
edition = "2018"

description = "A lock-free, eventually consistent, concurrent multi-value map."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/evmap"
homepage = "https://github.com/jonhoo/rust-evmap"
repository = "https://github.com/jonhoo/rust-evmap.git"

keywords = ["map","multi-value","lock-free"]
categories = ["concurrency", "data-structures"]

license = "MIT/Apache-2.0"

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "evmap", build = "8" }
codecov = { repository = "jonhoo/rust-evmap", branch = "master", service = "github" }
maintenance = { status = "passively-maintained" }

[dependencies]
smallvec = { version = "0.6.7", optional = true }
bytes = { version = "0.4.12", optional = true }

[features]
default = ["smallvec"]
nightly_smallvec = ["smallvec/union", "smallvec/may_dangle", "smallvec/specialization"]
